/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.loja.app.view;

import br.edu.ifms.loja.components.JImagePanel;
import br.ifms.edu.lpii.app.utils.ImagemUtils;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultDesktopManager;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author Gustavo
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private JanelaInternaVendas janelaInternaVendas;
    private JanelaInternaCadastros janelaInternaCadastros;

    public JanelaPrincipal() {
        
        initComponents();
        setTitle("Sistema de Vendas 1.0 - Trabalho Linguagem de Programação III");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        janelaInternaVendas = JanelaInternaVendas.getInstance();
        janelaInternaCadastros = JanelaInternaCadastros.getInstance();

        painelPrincipal.add(janelaInternaVendas);
        painelPrincipal.add(janelaInternaCadastros);
        painelPrincipal.setDesktopManager(new DefaultDesktopManager());
        painelPrincipal.setDragMode(JDesktopPane.LIVE_DRAG_MODE);

        try {
            botaoCadastros.setIcon(new ImageIcon(ImagemUtils.loadImage("img\\icons\\office-material-2.png")));
            botaoVendas.setIcon(new ImageIcon(ImagemUtils.loadImage("img\\icons\\online-store.png")));
            botaoConfiguracoes.setIcon(new ImageIcon(ImagemUtils.loadImage("img\\icons\\check-box.png")));
            logoFascom.setIcon(new ImageIcon(ImagemUtils.loadImage("img\\logolpIII.png")));
        } catch (IOException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jPanel1 = new JImagePanel(ImagemUtils.loadImage("img\\principal-bg.jpg"));
            jSplitPane1 = new javax.swing.JSplitPane();
            try{
                painelBotoes = new JImagePanel(ImagemUtils.loadImage("img\\gradient-bg.png"));
                botaoVendas = new javax.swing.JButton();
                botaoCadastros = new javax.swing.JButton();
                botaoConfiguracoes = new javax.swing.JButton();
                logoFascom = new javax.swing.JLabel();
                painelPrincipal = new javax.swing.JDesktopPane();
                try{
                    jPanel2 = new JImagePanel(ImagemUtils.loadImage("img\\logotipo-tsi.png"));
                    jMenuBar1 = new javax.swing.JMenuBar();
                    jMenu1 = new javax.swing.JMenu();
                    jMenu2 = new javax.swing.JMenu();
                    jMenu3 = new javax.swing.JMenu();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                } catch (IOException ex) {
                    Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

                jSplitPane1.setBorder(null);
                jSplitPane1.setDividerLocation(140);
                jSplitPane1.setDividerSize(2);
                jSplitPane1.setOpaque(false);

            } catch (IOException ex) {
                Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            painelBotoes.setOpaque(false);

            botaoVendas.setText("Vendas");
            botaoVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            botaoVendas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            botaoVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            botaoVendas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    acaoBotaoVendas(evt);
                }
            });

            botaoCadastros.setText("Cadastros");
            botaoCadastros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            botaoCadastros.setIconTextGap(0);
            botaoCadastros.setInheritsPopupMenu(true);
            botaoCadastros.setOpaque(false);
            botaoCadastros.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            botaoCadastros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            botaoCadastros.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    acaoBotaoCadastros(evt);
                }
            });

            botaoConfiguracoes.setText("Configurações");
            botaoConfiguracoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            botaoConfiguracoes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            botaoConfiguracoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            botaoConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    acaoBotaoConfiguracoes(evt);
                }
            });

            logoFascom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
            painelBotoes.setLayout(painelBotoesLayout);
            painelBotoesLayout.setHorizontalGroup(
                painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelBotoesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoConfiguracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(botaoCadastros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
                .addComponent(logoFascom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            painelBotoesLayout.setVerticalGroup(
                painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelBotoesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botaoCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botaoConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                    .addComponent(logoFascom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            painelBotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoCadastros, botaoConfiguracoes, botaoVendas});

            jSplitPane1.setLeftComponent(painelBotoes);

            painelPrincipal.setOpaque(false);

            JImagePanel jp =(JImagePanel)jPanel2;
            jp.setFillType(JImagePanel.FillType.CENTER);
        }catch (IOException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelPrincipal.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jSplitPane1.setRightComponent(painelPrincipal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acaoBotaoConfiguracoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoBotaoConfiguracoes
        // TODO add your handling code here:
    }//GEN-LAST:event_acaoBotaoConfiguracoes

    private void acaoBotaoCadastros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoBotaoCadastros
        janelaInternaCadastros.setVisible(true);
        painelPrincipal.setSelectedFrame(janelaInternaCadastros);        // TODO add your handling code here:
    }//GEN-LAST:event_acaoBotaoCadastros

    private void acaoBotaoVendas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoBotaoVendas
        janelaInternaVendas.setVisible(true);
        painelPrincipal.setSelectedFrame(janelaInternaVendas);
    }//GEN-LAST:event_acaoBotaoVendas

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastros;
    private javax.swing.JButton botaoConfiguracoes;
    private javax.swing.JButton botaoVendas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel logoFascom;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
