/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.loja.app.view;

import br.edu.ifms.loja.cidade.bo.CidadeBO;
import br.edu.ifms.loja.cidade.bo.CidadeController;
import br.edu.ifms.loja.cidade.view.CidadeForm;
import br.edu.ifms.loja.cidade.view.CidadeView;
import br.edu.ifms.loja.cliente.bo.ClienteBO;
import br.edu.ifms.loja.cliente.bo.ClienteController;
import br.edu.ifms.loja.cliente.view.ClienteView;
import br.edu.ifms.loja.cliente.view.FormCliente;
import br.edu.ifms.loja.fornecedor.bo.FornecedorBO;
import br.edu.ifms.loja.fornecedor.bo.FornecedorController;
import br.edu.ifms.loja.fornecedor.view.FornecedorForm;
import br.edu.ifms.loja.fornecedor.view.FornecedorView;
import br.edu.ifms.loja.produto.bo.ProdutoBO;
import br.edu.ifms.loja.produto.bo.ProdutoController;
import br.edu.ifms.loja.produto.view.FormProduto;
import br.edu.ifms.loja.produto.view.ProdutoView;
import br.edu.ifms.loja.uf.bo.UfBO;
import br.edu.ifms.loja.uf.bo.UfController;
import br.edu.ifms.loja.uf.view.FormUf;
import br.edu.ifms.loja.uf.view.UfView;
import br.edu.ifms.loja.usuario.bo.UsuarioBO;
import br.edu.ifms.loja.usuario.bo.UsuarioController;
import br.edu.ifms.loja.usuario.view.FormUsuario;
import br.edu.ifms.loja.usuario.view.UsuarioView;
import br.ifms.edu.lpii.app.utils.ImagemUtils;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JanelaInternaCadastros extends javax.swing.JInternalFrame {

    private final String CAMINHO_ICONES = "img\\icons";
    private final String ICONE_CLIENTES = "network.png";
    private final String ICONE_PRODUTOS = "packing-3.png";
    private final String ICONE_USUARIOS = "id-card.png";
    private final String ICONE_FORNECEDORES = "trucking.png";
    private final String ICONE_UF = "map.png";
    private final String ICONE_CIDADE = "cityscape.png";

    public static JanelaInternaCadastros janelaInternaVendas;

    private JanelaInternaCadastros() {
        initComponents();
        setTitle("Cadastros");
        setDefaultCloseOperation(JInternalFrame.HIDE_ON_CLOSE);
        setClosable(true);
        carregarIcones();
    }

    public static JanelaInternaCadastros getInstance() {
        if (janelaInternaVendas == null) {
            janelaInternaVendas = new JanelaInternaCadastros();
        }
        return janelaInternaVendas;
    }

    private void carregarIcones() {
        try {
            ImageIcon clientes = new ImageIcon(ImagemUtils.loadImage(CAMINHO_ICONES + "\\" + ICONE_CLIENTES));
            botaoClientes.setIcon(clientes);

            ImageIcon fornecedores = new ImageIcon(ImagemUtils.loadImage(CAMINHO_ICONES + "\\" + ICONE_FORNECEDORES));
            botaoFornecedores.setIcon(fornecedores);

            ImageIcon produtos = new ImageIcon(ImagemUtils.loadImage(CAMINHO_ICONES + "\\" + ICONE_PRODUTOS));
            botaoProdutos.setIcon(produtos);

            ImageIcon usuarios = new ImageIcon(ImagemUtils.loadImage(CAMINHO_ICONES + "\\" + ICONE_USUARIOS));
            botaoUsuarios.setIcon(usuarios);
            
            ImageIcon cidades = new ImageIcon(ImagemUtils.loadImage(CAMINHO_ICONES + "\\" + ICONE_CIDADE));
            botaoCidades.setIcon(cidades);
            
            ImageIcon ufs = new ImageIcon(ImagemUtils.loadImage(CAMINHO_ICONES + "\\" + ICONE_UF));
            botaoUFs.setIcon(ufs);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Impossível carregar icones de botões!", "Problema", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoProdutos = new javax.swing.JButton();
        botaoClientes = new javax.swing.JButton();
        botaoUsuarios = new javax.swing.JButton();
        botaoFornecedores = new javax.swing.JButton();
        botaoUFs = new javax.swing.JButton();
        botaoCidades = new javax.swing.JButton();

        botaoProdutos.setText("Produtos");
        botaoProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutosActionPerformed(evt);
            }
        });

        botaoClientes.setText("Clientes");
        botaoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClientesActionPerformed(evt);
            }
        });

        botaoUsuarios.setText("Usuarios");
        botaoUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuariosActionPerformed(evt);
            }
        });

        botaoFornecedores.setText("Fornecedores");
        botaoFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFornecedoresActionPerformed(evt);
            }
        });

        botaoUFs.setText("UFs");
        botaoUFs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoUFs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoUFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUFsActionPerformed(evt);
            }
        });

        botaoCidades.setText("Cidades");
        botaoCidades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCidades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoUFs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botaoClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoUFs, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClientesActionPerformed
        ClienteBO model = new ClienteBO();
        FormCliente form = new FormCliente();
        ClienteView view = new ClienteView(form);
        ClienteController controller = new ClienteController(model, view);
        view.setVisible(true);
    }//GEN-LAST:event_botaoClientesActionPerformed

    private void botaoFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFornecedoresActionPerformed
        FornecedorBO model = new FornecedorBO();
        FornecedorForm form = new FornecedorForm();
        FornecedorView view = new FornecedorView(form);
        FornecedorController controller = new FornecedorController(model,view);
        view.setVisible(true);
    }//GEN-LAST:event_botaoFornecedoresActionPerformed

    private void botaoUFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUFsActionPerformed
        UfBO model = new UfBO();
        FormUf form = new FormUf();
        UfView view = new UfView(form);
        UfController controller = new UfController(model, view);
        view.setVisible(true);
    }//GEN-LAST:event_botaoUFsActionPerformed

    private void botaoCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCidadesActionPerformed
        CidadeBO model = new CidadeBO();
        CidadeForm form = new CidadeForm();
        CidadeView view = new CidadeView(form);
        CidadeController controller = new CidadeController(model, view);
        view.setVisible(true);
    }//GEN-LAST:event_botaoCidadesActionPerformed

    private void botaoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUsuariosActionPerformed
        UsuarioBO model = new UsuarioBO();
        FormUsuario form = new FormUsuario();
        UsuarioView view = new UsuarioView(form);
        UsuarioController controller = new UsuarioController(model, view);
        view.setVisible(true);
    }//GEN-LAST:event_botaoUsuariosActionPerformed

    private void botaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutosActionPerformed
        ProdutoBO model = new ProdutoBO();
        FormProduto form = new FormProduto();
        ProdutoView view = new ProdutoView(form);
        ProdutoController controller = new ProdutoController(model, view);
        view.setVisible(true);
    }//GEN-LAST:event_botaoProdutosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCidades;
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoFornecedores;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JButton botaoUFs;
    private javax.swing.JButton botaoUsuarios;
    // End of variables declaration//GEN-END:variables
}
